services:
  parser:
    build:
      context: ./services/parser
      dockerfile: Dockerfile
    depends_on:
      - db
    networks:
      - eunice_challenge
    container_name: eunice_challenge_parser
