services:
  parser:
    build:
      context: ./services/parser
      dockerfile: Dockerfile
    depends_on:
      - db
    networks:
      - eunice_challenge
    volumes:
      - ./services/parser:/parser
    environment:
      - PYTHONPATH=/parser
    container_name: eunice_challenge_parser
